markdown: kramdown
exclude: 
  - tmp/
  - vendor/
  - README.md
  - LICENSE
  - make_pdf.rb 
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - .dockerignore
  - _pdfbuild
plugins:
  - "jekyll-github-metadata"
